# Generated by Django 3.0.4 on 2021-01-10 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='category_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_obj', to='product.Category'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='product_obj',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_obj', to='product.Product'),
        ),
    ]
