# Generated by Django 3.0.4 on 2021-01-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210110_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='product.Product'),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
