# Generated by Django 3.0.4 on 2021-01-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210110_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ratings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
