# Generated by Django 3.0.4 on 2021-01-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0002_auto_20210110_2050'),
        ('product', '0006_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_staff', to='staffs.Staff'),
        ),
    ]
