# Generated by Django 3.0.4 on 2021-01-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210110_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_type',
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='product.Category'),
        ),
    ]
