# Generated by Django 3.0.4 on 2021-01-11 14:07

from django.db import migrations, models
import imagekit.models.fields
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210111_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='image/default_user.png', null=True, upload_to=product.models.upload_location),
        ),
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='default_user.png'),
        ),
    ]
