# Generated by Django 3.0.8 on 2021-01-22 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20210111_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('context_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'food_types',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='food_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='food_type', to='product.FoodType'),
            preserve_default=False,
        ),
    ]
