# Generated by Django 3.0.8 on 2021-01-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210122_2339'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('title', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='foodtype',
            unique_together={('title', 'slug')},
        ),
    ]
