# Generated by Django 3.0.4 on 2021-01-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('country_code', models.CharField(max_length=8)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('otp', models.CharField(blank=True, max_length=10, null=True)),
                ('otp_sent_at', models.DateTimeField(null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_type', models.CharField(choices=[('REGISTRATION', 'registration'), ('BOOKING', 'booking'), ('LOGIN', 'login'), ('RESET_PASSWORD', 'reset_password')], default='REGISTRATION', max_length=25)),
            ],
            options={
                'db_table': 'otps',
            },
        ),
    ]
