# Generated by Django 3.0.4 on 2021-01-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='employee_id',
            new_name='employee_code',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employer_content_type',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='employer_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='user_category',
            field=models.CharField(blank=True, choices=[('VENDOR', 'Vendor'), ('DELIVERY', 'Deliver')], max_length=20, null=True),
        ),
    ]
