# Generated by Django 3.0.8 on 2021-01-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('product', '0011_auto_20210126_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0)),
                ('net_amout', models.FloatField(default=0)),
                ('gross_amount', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('offer', models.FloatField(default=0)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('date_dispatch', models.DateTimeField(blank=True, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('INACTIVE', 'InActive'), ('BOOKINGCMPLTD', 'Booking Completed'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=100)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Product')),
                ('user_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_customer', to='customer.Customer')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
